export const LOAD_ALL_LISTS_START = 'LOAD_ALL_LISTS_START';
export const LOAD_ALL_LISTS_SUCCESS = 'LOAD_ALL_LISTS_SUCCESS';
export const LOAD_ALL_LISTS_FAIL = 'LOAD_ALL_LISTS_FAIL';

export const ADD_LIST = 'ADD_LIST';

export const LOAD_LIST_START = 'LOAD_LIST_START';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const LOAD_LIST_FAIL = 'LOAD_LIST_FAIL';

export const SET_USER = 'SET_USER';